// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addCocktail.sql

package database

import (
	"context"
	"database/sql"
)

const addCocktail = `-- name: AddCocktail :one
INSERT INTO cocktails (id, created_at, updated_at, data_url, base_spirit, cocktail_type, name) 
VALUES (
	gen_random_uuid(),
	now(),
	now(),
	$1,
	$2,
	$3,
	$4
)
RETURNING id, created_at, updated_at, data_url, base_spirit, cocktail_type, name
`

type AddCocktailParams struct {
	DataUrl      sql.NullString
	BaseSpirit   string
	CocktailType string
	Name         string
}

func (q *Queries) AddCocktail(ctx context.Context, arg AddCocktailParams) (Cocktail, error) {
	row := q.db.QueryRowContext(ctx, addCocktail,
		arg.DataUrl,
		arg.BaseSpirit,
		arg.CocktailType,
		arg.Name,
	)
	var i Cocktail
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DataUrl,
		&i.BaseSpirit,
		&i.CocktailType,
		&i.Name,
	)
	return i, err
}
