// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addCocktail.sql

package database

import (
	"context"
	"database/sql"
)

const addCocktail = `-- name: AddCocktail :one
INSERT INTO cocktails (id, created_at, updated_at, data_url, base_spirit, cocktail_type, name, img_name, type, is_new) 
VALUES (
	gen_random_uuid(),
	now(),
	now(),
	Null,
	$1,
	$2,
	$3,
	$4,
	$5,
	false
)
RETURNING id, created_at, updated_at, data_url, base_spirit, cocktail_type, name, img_name, type, is_new, is_mocktail, is_available
`

type AddCocktailParams struct {
	BaseSpirit   string
	CocktailType string
	Name         string
	ImgName      sql.NullString
	Type         sql.NullString
}

func (q *Queries) AddCocktail(ctx context.Context, arg AddCocktailParams) (Cocktail, error) {
	row := q.db.QueryRowContext(ctx, addCocktail,
		arg.BaseSpirit,
		arg.CocktailType,
		arg.Name,
		arg.ImgName,
		arg.Type,
	)
	var i Cocktail
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DataUrl,
		&i.BaseSpirit,
		&i.CocktailType,
		&i.Name,
		&i.ImgName,
		&i.Type,
		&i.IsNew,
		&i.IsMocktail,
		&i.IsAvailable,
	)
	return i, err
}
