// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addIngredient.sql

package database

import (
	"context"
)

const addIngredient = `-- name: AddIngredient :one
INSERT INTO ingredients(id, name, abv, is_available, created_at, modified_at) 
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	TRUE,
	now(),
	now()
)
RETURNING id, name, abv, is_available, created_at, modified_at
`

type AddIngredientParams struct {
	Name string
	Abv  float32
}

func (q *Queries) AddIngredient(ctx context.Context, arg AddIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, addIngredient, arg.Name, arg.Abv)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abv,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
