// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addRecipieIngr.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addRecipIngr = `-- name: AddRecipIngr :one
INSERT INTO recipies(cocktail_id, ingredient_id, amount, unit, created_at, modified_at)
VALUES (
	$1,
	$2,
	$3,
	$4,
	now(),
	now()
)
RETURNING cocktail_id, ingredient_id, amount, unit, created_at, modified_at
`

type AddRecipIngrParams struct {
	CocktailID   uuid.UUID
	IngredientID uuid.UUID
	Amount       int32
	Unit         string
}

func (q *Queries) AddRecipIngr(ctx context.Context, arg AddRecipIngrParams) (Recipy, error) {
	row := q.db.QueryRowContext(ctx, addRecipIngr,
		arg.CocktailID,
		arg.IngredientID,
		arg.Amount,
		arg.Unit,
	)
	var i Recipy
	err := row.Scan(
		&i.CocktailID,
		&i.IngredientID,
		&i.Amount,
		&i.Unit,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
