// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addRecipie.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addRecipie = `-- name: AddRecipie :one
INSERT INTO ingredients(id, name, quantity, abv, created_at, modified_at, cocktail_id) 
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	$3,
	now(),
	now(),
	$4
)
RETURNING id, name, quantity, abv, created_at, modified_at, cocktail_id
`

type AddRecipieParams struct {
	Name       string
	Quantity   int32
	Abv        float32
	CocktailID uuid.UUID
}

func (q *Queries) AddRecipie(ctx context.Context, arg AddRecipieParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, addRecipie,
		arg.Name,
		arg.Quantity,
		arg.Abv,
		arg.CocktailID,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Abv,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CocktailID,
	)
	return i, err
}
