// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cancelOrder.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET canceled_at = now(), modified_at = now()
where id = $1
RETURNING id, created_at, modified_at, cocktail_id, ordered_by, canceled_at, finished
`

func (q *Queries) CancelOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, cancelOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CocktailID,
		&i.OrderedBy,
		&i.CanceledAt,
		&i.Finished,
	)
	return i, err
}
