// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkCocktail.sql

package database

import (
	"context"
)

const checkCocktail = `-- name: CheckCocktail :one
SELECT count(*) FROM cocktails
WHERE name = $1
`

func (q *Queries) CheckCocktail(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCocktail, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
