// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkIngredients.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getIngredients = `-- name: GetIngredients :many
select id, name
from ingredients
where name = ANY($1::text[])
`

type GetIngredientsRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetIngredients(ctx context.Context, dollar_1 []string) ([]GetIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIngredients, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientsRow
	for rows.Next() {
		var i GetIngredientsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
