// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: createUser.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, name, created_at, modified_at, last_seen_at)
VALUES (
	gen_random_uuid(),
	$1,
	now(),
	now(),
	now()
)
RETURNING id, name, created_at, modified_at, last_seen_at
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.LastSeenAt,
	)
	return i, err
}
