// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currentOrders.sql

package database

import (
	"context"
)

const getCurrentOrders = `-- name: GetCurrentOrders :many
SELECT id, created_at, modified_at, cocktail_id, ordered_by, canceled_at, finished 
FROM orders 
WHERE canceled_at is null
and finished = false
`

func (q *Queries) GetCurrentOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.CocktailID,
			&i.OrderedBy,
			&i.CanceledAt,
			&i.Finished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
