// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getAllCocktailTypes.sql

package database

import (
	"context"
	"database/sql"
)

const getCocktailTypes = `-- name: GetCocktailTypes :many
SELECT distinct type FROM cocktails
`

func (q *Queries) GetCocktailTypes(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getCocktailTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var type_ sql.NullString
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
