// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getAllCocktails.sql

package database

import (
	"context"
)

const getAllCock = `-- name: GetAllCock :many
SELECT id, created_at, updated_at, data_url, base_spirit, cocktail_type, name, img_name, type, is_new FROM cocktails
`

func (q *Queries) GetAllCock(ctx context.Context) ([]Cocktail, error) {
	rows, err := q.db.QueryContext(ctx, getAllCock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cocktail
	for rows.Next() {
		var i Cocktail
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DataUrl,
			&i.BaseSpirit,
			&i.CocktailType,
			&i.Name,
			&i.ImgName,
			&i.Type,
			&i.IsNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
