// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getAllCocktailImgs.sql

package database

import (
	"context"
	"database/sql"
)

const getCocktailImgs = `-- name: GetCocktailImgs :many
SELECT distinct img_name FROM cocktails
`

func (q *Queries) GetCocktailImgs(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getCocktailImgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var img_name sql.NullString
		if err := rows.Scan(&img_name); err != nil {
			return nil, err
		}
		items = append(items, img_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
