// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getCockData.sql

package database

import (
	"context"
)

const getCocktail = `-- name: GetCocktail :one
SELECT id, created_at, updated_at, data_url, base_spirit, cocktail_type, name, img_name, type, is_new, is_mocktail, is_available FROM cocktails
WHERE name = $1
`

func (q *Queries) GetCocktail(ctx context.Context, name string) (Cocktail, error) {
	row := q.db.QueryRowContext(ctx, getCocktail, name)
	var i Cocktail
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DataUrl,
		&i.BaseSpirit,
		&i.CocktailType,
		&i.Name,
		&i.ImgName,
		&i.Type,
		&i.IsNew,
		&i.IsMocktail,
		&i.IsAvailable,
	)
	return i, err
}
