// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getCockIngr.sql

package database

import (
	"context"
	"database/sql"
)

const getCocksIngr = `-- name: GetCocksIngr :many
select cock.name 
from ingredients ingr
left join recipies rec on rec.ingredient_id = ingr.id
left join cocktails cock on cock.id = rec.cocktail_id
where ingr.name = $1
`

func (q *Queries) GetCocksIngr(ctx context.Context, name string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getCocksIngr, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var name sql.NullString
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
