// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getCockData.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCocktail = `-- name: GetCocktail :one
SELECT id, created_at, updated_at, data_url, base_spirit, cocktail_type, name FROM cocktails
WHERE id = $1
`

func (q *Queries) GetCocktail(ctx context.Context, id uuid.NullUUID) (Cocktail, error) {
	row := q.db.QueryRowContext(ctx, getCocktail, id)
	var i Cocktail
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DataUrl,
		&i.BaseSpirit,
		&i.CocktailType,
		&i.Name,
	)
	return i, err
}
