// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getCockSearch.sql

package database

import (
	"context"
	"database/sql"
)

const getCockSearch = `-- name: GetCockSearch :many
SELECT id, created_at, updated_at, data_url, base_spirit, cocktail_type, name, img_name, type, is_new, is_mocktail, is_available 
FROM cocktails
WHERE name like '%' || $1 || '%'
order by is_new desc, name
`

func (q *Queries) GetCockSearch(ctx context.Context, dollar_1 sql.NullString) ([]Cocktail, error) {
	rows, err := q.db.QueryContext(ctx, getCockSearch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cocktail
	for rows.Next() {
		var i Cocktail
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DataUrl,
			&i.BaseSpirit,
			&i.CocktailType,
			&i.Name,
			&i.ImgName,
			&i.Type,
			&i.IsNew,
			&i.IsMocktail,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
