// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getCocktailName.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCocktailName = `-- name: GetCocktailName :one
SELECT id, created_at, updated_at, data_url, base_spirit, cocktail_type, name, img_name, type, is_new, is_mocktail, is_available FROM cocktails
WHERE id = $1
`

func (q *Queries) GetCocktailName(ctx context.Context, id uuid.NullUUID) (Cocktail, error) {
	row := q.db.QueryRowContext(ctx, getCocktailName, id)
	var i Cocktail
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DataUrl,
		&i.BaseSpirit,
		&i.CocktailType,
		&i.Name,
		&i.ImgName,
		&i.Type,
		&i.IsNew,
		&i.IsMocktail,
		&i.IsAvailable,
	)
	return i, err
}
