// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getFullRecipe.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getFullRecipie = `-- name: GetFullRecipie :many
select ingr.name, rc.amount, rc.unit
from recipies rc
left join ingredients ingr on rc.ingredient_id = ingr.id
where rc.cocktail_id = $1
`

type GetFullRecipieRow struct {
	Name   sql.NullString
	Amount int32
	Unit   string
}

func (q *Queries) GetFullRecipie(ctx context.Context, cocktailID uuid.UUID) ([]GetFullRecipieRow, error) {
	rows, err := q.db.QueryContext(ctx, getFullRecipie, cocktailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullRecipieRow
	for rows.Next() {
		var i GetFullRecipieRow
		if err := rows.Scan(&i.Name, &i.Amount, &i.Unit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
