// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getFullOrders.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getFullOrders = `-- name: GetFullOrders :many
SELECT  ord.id, 
	ord.ordered_by,
	ord.created_at,
	ord.cocktail_id,
	ing.id,
	ing.name,
	ing.quantity,
	ing.abv     
FROM orders ord 
LEFT OUTER JOIN ingredients ing on ing.cocktail_id = ord.cocktail_id
WHERE ord.canceled_at is null
and ord.finished = false
`

type GetFullOrdersRow struct {
	ID         uuid.UUID
	OrderedBy  string
	CreatedAt  time.Time
	CocktailID uuid.UUID
	ID_2       uuid.NullUUID
	Name       sql.NullString
	Quantity   sql.NullInt32
	Abv        sql.NullFloat64
}

func (q *Queries) GetFullOrders(ctx context.Context) ([]GetFullOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getFullOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullOrdersRow
	for rows.Next() {
		var i GetFullOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderedBy,
			&i.CreatedAt,
			&i.CocktailID,
			&i.ID_2,
			&i.Name,
			&i.Quantity,
			&i.Abv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
