// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getMyOrders.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getMyOrders = `-- name: GetMyOrders :many
select ord.id, ord.created_at, ord.canceled_at, ord.finished,  cock.name, cock.img_name
from orders ord
left join cocktails cock on cock.id = ord.cocktail_id
where ord.ordered_by = $1
order by ord.created_at desc
`

type GetMyOrdersRow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	CanceledAt sql.NullTime
	Finished   sql.NullBool
	Name       sql.NullString
	ImgName    sql.NullString
}

func (q *Queries) GetMyOrders(ctx context.Context, orderedBy string) ([]GetMyOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getMyOrders, orderedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyOrdersRow
	for rows.Next() {
		var i GetMyOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CanceledAt,
			&i.Finished,
			&i.Name,
			&i.ImgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
