// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getRanking.sql

package database

import (
	"context"
)

const getRanking = `-- name: GetRanking :many
select cast(sum(ingr.abv * rec.amount) / 100 as DOUBLE PRECISION)as score, ord.ordered_by
from orders ord
left join recipies rec on rec.cocktail_id = ord.cocktail_id
left join ingredients ingr on ingr.id = rec.ingredient_id
where ord.finished = true
group by ord.ordered_by
order by score desc
`

type GetRankingRow struct {
	Score     float64
	OrderedBy string
}

func (q *Queries) GetRanking(ctx context.Context) ([]GetRankingRow, error) {
	rows, err := q.db.QueryContext(ctx, getRanking)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRankingRow
	for rows.Next() {
		var i GetRankingRow
		if err := rows.Scan(&i.Score, &i.OrderedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
