// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getRecipie.sql

package database

import (
	"context"
)

const getRecipie = `-- name: GetRecipie :many
SELECT ing.id, ing.name, ing.abv, ing.is_available, ing.created_at, ing.modified_at 
FROM ingredients ing  
INNER JOIN cocktails cock on cock.ID = ing.cocktail_ID
WHERE $1 = cock.Name
`

func (q *Queries) GetRecipie(ctx context.Context, name string) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, getRecipie, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Abv,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
