// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getRecipie.sql

package database

import (
	"context"
	"database/sql"
)

const getRecipie = `-- name: GetRecipie :many
select ingr.name
from cocktails cock
left join recipies rec on rec.cocktail_id = cock.id
left join ingredients ingr on ingr.id = rec.ingredient_id
where cock.name = $1 
and ingr.id is not null
`

func (q *Queries) GetRecipie(ctx context.Context, name string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getRecipie, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var name sql.NullString
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
