// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserFromId = `-- name: GetUserFromId :one
SELECT id, name, created_at, modified_at, last_seen_at FROM users 
WHERE id = $1
`

func (q *Queries) GetUserFromId(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromId, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.LastSeenAt,
	)
	return i, err
}
