// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cocktail struct {
	ID           uuid.NullUUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DataUrl      sql.NullString
	BaseSpirit   string
	CocktailType string
	Name         string
}

type Order struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	ModifiedAt sql.NullTime
	CocktailID uuid.UUID
	OrderedBy  string
	CanceledAt sql.NullTime
	Finished   sql.NullBool
}
