// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cocktail struct {
	ID           uuid.NullUUID
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DataUrl      sql.NullString
	BaseSpirit   string
	CocktailType string
	Name         string
	ImgName      sql.NullString
	Type         sql.NullString
	IsNew        bool
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    time.Time
}

type Ingredient struct {
	ID          uuid.UUID
	Name        string
	Abv         float32
	IsAvailable bool
	CreatedAt   time.Time
	ModifiedAt  sql.NullTime
}

type Order struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	ModifiedAt sql.NullTime
	CocktailID uuid.UUID
	OrderedBy  string
	CanceledAt sql.NullTime
	Finished   sql.NullBool
}

type Recipy struct {
	CocktailID   uuid.UUID
	IngredientID uuid.UUID
	Amount       int32
	Unit         string
	CreatedAt    time.Time
	ModifiedAt   sql.NullTime
}
