// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sendOrder.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const sendOrder = `-- name: SendOrder :one
INSERT INTO orders (id, created_at, modified_at, cocktail_id, ordered_by, canceled_at, finished)
VALUES (
	gen_random_uuid(),
	now(),
	now(),
	$1,
	$2,
	NULL,
	false
)
RETURNING id, created_at, modified_at, cocktail_id, ordered_by, canceled_at, finished
`

type SendOrderParams struct {
	CocktailID uuid.UUID
	OrderedBy  string
}

func (q *Queries) SendOrder(ctx context.Context, arg SendOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, sendOrder, arg.CocktailID, arg.OrderedBy)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.CocktailID,
		&i.OrderedBy,
		&i.CanceledAt,
		&i.Finished,
	)
	return i, err
}
