// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateCocktailUnavailabilty.sql

package database

import (
	"context"
)

const updateUnavCock = `-- name: UpdateUnavCock :exec
UPDATE cocktails 
SET is_available = false , updated_at = now()
where cocktails.id in (
  select cock.id
  from cocktails cock 
  left join recipies rec on rec.cocktail_id = cock.id 
  left join ingredients ingr on ingr.id = rec.ingredient_id
  where ingr.is_available = false)
`

func (q *Queries) UpdateUnavCock(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateUnavCock)
	return err
}
