// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateIngredient.sql

package database

import (
	"context"
)

const updateIngr = `-- name: UpdateIngr :one
UPDATE ingredients 
SET is_available =$1 , modified_at = now()
where name = $2
RETURNING id, name, abv, is_available, created_at, modified_at
`

type UpdateIngrParams struct {
	IsAvailable bool
	Name        string
}

func (q *Queries) UpdateIngr(ctx context.Context, arg UpdateIngrParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, updateIngr, arg.IsAvailable, arg.Name)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abv,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
