// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BarIndex() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><title>HomeBar - Bar Side</title><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, inital-scale=1.0\"><script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js\"></script><script src=\"https://cdn.tailwindcss.com\"></script><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\"><style>\n        \t\t\tbody { font-family: 'Inter', sans-serif; }\n    \t\t\t</style></head><body id=\"main-bar\" class=\"bg-stone-200 min-h-screen p-6\"><div class=\"flex justify-between items-center mb-8 border-b-2 border-stone-400 pb-4\"><h1 class=\"text-3xl font-bold text-stone-800 uppercase tracking-widest\">Kitchen side</h1><button hx-get=\"/currentOrders\" hx-target=\"#current-orders\" class=\"bg-stone-800 text-white px-4 py-2 text-sm uppercase font-bold hover:bg-black transition-colors\">Load the Orders</button> <button hx-get=\"/addRecipieForm\" hx-target=\"#current-orders\" class=\"bg-slate-700 text-white px-4 py-2 text-sm uppercase font-bold hover:bg-black transition-colors\">Add Cocktail Recipie</button></div><div id=\"current-orders\" class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6\" hx-get=\"/currentOrders\" hx-trigger=\"load\">Waiting for orders</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
