// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BarIndex() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = themeHead("唐変木テンダーさん").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</head><body id=\"main-bar\" class=\"washi-bg text-washi min-h-screen\"><div class=\"noren\"></div><header class=\"flex items-center justify-between px-6 py-5 border-b border-kin/30 max-w-7xl mx-auto\"><h1 class=\"font-mincho text-2xl text-washi tracking-[0.3em]\">厨房</h1><nav class=\"flex gap-6\"><button hx-get=\"/ingredients\" hx-target=\"#current-orders\" class=\"font-mincho text-sm text-washi-dim hover:text-kin tracking-widest transition-colors\">材料</button> <button hx-get=\"/currentOrders\" hx-target=\"#current-orders\" class=\"font-mincho text-sm text-shu border border-shu px-4 py-1 hover:bg-shu hover:text-sumi transition-colors tracking-widest\">注文一覧</button> <button hx-get=\"/addRecipieForm\" hx-target=\"#current-orders\" class=\"font-mincho text-sm text-washi-dim hover:text-kin tracking-widest transition-colors\">献立追加</button></nav></header><main id=\"current-orders\" class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 p-6 max-w-7xl mx-auto\" hx-get=\"/currentOrders\" hx-trigger=\"load\"><p class=\"font-mincho text-washi-dim col-span-full text-center py-12 italic\">注文を待っています…</p></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
