// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func RecipieForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form hx-post=\"/addRecipie\" hx-target=\"#bar-area\" class=\"space-y-4\"><label for=\"CocktailName\" class=\"block text-sm font-medium text-slate-700 mb-1\">Cocktail Name</label> <input type=\"text\" class=\"w-full px-3 py-2 bg-slate-200 text-slate-900 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500\" name=\"cocktailName\"> <label for=\"Ingredient 1\" class=\"block text-sm font-medium text-slate-700 mb-1\">Ingredients:</label> <input type=\"text\" class=\"w-full px-3 py-2 bg-slate-200 text-slate-900 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500\" name=\"cocktailName\"> <input type=\"text\" class=\"w-full px-3 py-2 bg-slate-200 text-slate-900 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500\" name=\"cocktailName\"> <input type=\"text\" name=\"customerName\" class=\"w-full px-3 py-2 bg-slate-200 text-slate-900 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500\"> <button type=\"submit\" class=\"w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-3 rounded-lg shadow-md transition-transform active:scale-95\">注文する</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
